spring.application.name=oop

spring.datasource.url=jdbc:postgresql://34.116.139.234:5432/sw_db
spring.datasource.username=postgres
spring.datasource.password=Kakashka123.
spring.jpa.hibernate.ddl-auto=update
server.port=${PORT:8080}

#spring.datasource.url=jdbc:postgresql://localhost:5432/StardewValleyDB
#spring.datasource.username=postgres
#spring.datasource.password=123456789
#
#spring.jpa.hibernate.ddl-auto=update
server.forward-headers-strategy=framework
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jackson.serialization.fail-on-empty-beans=false

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=profile,email