spring.application.name=oop

spring.datasource.url=jdbc:postgresql://34.116.139.234:5432/sw_db
spring.datasource.username=postgres
spring.datasource.password=Kakashka123.
spring.jpa.hibernate.ddl-auto=update

#spring.datasource.url=jdbc:postgresql://localhost:5432/StardewValleyDB
#spring.datasource.username=postgres
#spring.datasource.password=123456789
#
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jackson.serialization.fail-on-empty-beans=false